# Generated by Django 6.0.7 on 2026-07-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Animales', 'Animales'), ('Insumos', 'Insumos'), ('Maquinaria', 'Maquinaria'), ('Otros', 'Otros')], max_length=50)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.proveedor')),
                ('mov_financiero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.movimientofinanciero')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.comprador')),
                ('mov_financiero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.movimientofinanciero')),
            ],
        ),
    ]
