# Generated by Django 6.0.7 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
