# Generated by Django 6.0.7 on 2026-08-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_venta_peso_total_venta_precio_por_kg'),
        ('usuarios', '0002_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.comprador'),
        ),
    ]
