# Generated by Django 6.0.7 on 2026-08-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_venta_comprador'),
        ('usuarios', '0008_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.proveedor'),
        ),
    ]
