# Generated by Django 6.0.7 on 2026-08-08 15:08

import django.db.models.deletion
from django.db import migrations, models


def asignar_establecimiento_único(apps, schema_editor):
    """Si existe un único establecimiento, se lo asigna a los movimientos sin establecer."""
    Establecimiento = apps.get_model('establecimientos', 'Establecimiento')
    MovimientoFinanciero = apps.get_model('finanzas', 'MovimientoFinanciero')
    establecimiento = Establecimiento.objects.first()
    if establecimiento is None or Establecimiento.objects.count() > 1:
        return
    MovimientoFinanciero.objects.filter(establecimiento__isnull=True).update(establecimiento=establecimiento)


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_establecimiento_logo'),
        ('finanzas', '0004_alter_compra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='establecimientos.establecimiento'),
        ),
        migrations.RunPython(asignar_establecimiento_único, migrations.RunPython.noop),
    ]
