# Generated by Django 6.0.7 on 2026-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_movimientofinanciero_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='porcentajeDesbaste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
