# Generated by Django 6.0.7 on 2026-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_venta_porcentajedesbaste'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estadoDePago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodoDePago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], default='Efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='estadoDeCobro',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodoDePago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], default='Efectivo', max_length=20),
        ),
    ]
