# Generated by Django 6.0.7 on 2026-08-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_establecimiento_logo'),
        ('finanzas', '0007_compra_estadodepago_compra_metododepago_and_more'),
        ('usuarios', '0008_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionSueldo',
            fields=[
                ('idLiquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de Liquidación')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo (Monto)')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción / Detalle')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='usuarios.usuario', verbose_name='Empleado')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_sueldos', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('movimiento_financiero', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion_origen', to='finanzas.movimientofinanciero', verbose_name='Movimiento Financiero Asociado')),
            ],
            options={
                'verbose_name': 'Liquidación de Sueldo',
                'verbose_name_plural': 'Liquidaciones de Sueldos',
                'ordering': ['-fecha'],
            },
        ),
    ]
