# Generated by Django 6.1 on 2026-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_liquidacionsueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
