# Generated by Django 6.0.7 on 2026-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_de_medida',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
