# Generated by Django 6.0.7 on 2026-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_dieta_ingredientes_insumo_unidad_de_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(choices=[('Vacuna', 'Vacuna'), ('Medicamento', 'Medicamento'), ('Alimento', 'Alimento'), ('Otros', 'Otros')], default='Otros', max_length=20),
        ),
    ]
