# Generated by Django 6.0.7 on 2026-08-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_insumo_options_insumo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composiciondieta',
            name='cantidad_por_porcion',
        ),
        migrations.RemoveField(
            model_name='composiciondieta',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='consumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='unidad_de_medida',
        ),
        migrations.AddField(
            model_name='composiciondieta',
            name='cantidadPorPorcion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='precioUnitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidadDeMedida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='composiciondieta',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composiciones', to='inventario.dieta'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Vacuna', 'Vacuna'), ('Medicamento', 'Medicamento'), ('Alimento', 'Alimento'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('stockActual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.insumo')),
            ],
            options={
                'ordering': ['fechaVencimiento', 'id'],
            },
        ),
        migrations.AddField(
            model_name='composiciondieta',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composiciones_dieta', to='inventario.lote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumo',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.lote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='inventario.lote'),
            preserve_default=False,
        ),
    ]
