# Generated by Django 6.0.7 on 2026-08-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_composiciondieta_cantidad_por_porcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={},
        ),
        migrations.AddField(
            model_name='lote',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
