# Generated by Django 6.0.7 on 2026-08-08 15:08

import django.db.models.deletion
from django.db import migrations, models


def asignar_establecimiento_único(apps, schema_editor):
    """Si existe un único establecimiento, se lo asigna a los lotes sin establecer."""
    Establecimiento = apps.get_model('establecimientos', 'Establecimiento')
    Lote = apps.get_model('inventario', 'Lote')
    establecimiento = Establecimiento.objects.first()
    if establecimiento is None or Establecimiento.objects.count() > 1:
        return
    Lote.objects.filter(establecimiento__isnull=True).update(establecimiento=establecimiento)


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_establecimiento_logo'),
        ('inventario', '0005_alter_lote_options_lote_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='establecimientos.establecimiento'),
        ),
        migrations.RunPython(asignar_establecimiento_único, migrations.RunPython.noop),
    ]
