# Generated by Django 5.2.2 on 2026-08-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0019_remove_animal_dieta'),
        ('inventario', '0007_insumo_activo_lote_activo_alter_lote_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroalimentacion',
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='registroalimentacion',
            name='parcela',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Vacuna', 'Vacuna'), ('Medicamento', 'Medicamento'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ComposicionDieta',
        ),
        migrations.DeleteModel(
            name='Dieta',
        ),
        migrations.DeleteModel(
            name='RegistroAlimentacion',
        ),
    ]
