# Generated by Django 6.0.7 on 2026-07-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preniez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Natural', 'Natural'), ('Inseminación', 'Inseminación')], max_length=20)),
                ('costo_inseminacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_actual', models.CharField(choices=[('Preñada', 'Preñada'), ('A confirmar', 'A confirmar'), ('Vacía', 'Vacía')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_senasa', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_al_nacer', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peso_al_destete', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vendido', models.BooleanField(default=False)),
                ('vivo', models.BooleanField(default=True)),
                ('enfermo', models.BooleanField(default=False)),
                ('tipo_animal', models.CharField(choices=[('Bovino', 'Bovino'), ('Porcino', 'Porcino'), ('Ovino', 'Ovino')], max_length=10)),
                ('sexo', models.IntegerField(choices=[(0, 'Macho'), (1, 'Hembra')])),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_madre', models.CharField(blank=True, max_length=100, null=True)),
                ('diametro_escrotal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.compra')),
            ],
        ),
    ]
