# Generated by Django 6.0.7 on 2026-07-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('establecimientos', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.dieta'),
        ),
        migrations.AddField(
            model_name='animal',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='animales.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimientos.parcela'),
        ),
        migrations.AddField(
            model_name='animal',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.venta'),
        ),
        migrations.AddField(
            model_name='preniez',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenieces_madre', to='animales.animal'),
        ),
        migrations.AddField(
            model_name='preniez',
            name='mov_financiero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.movimientofinanciero'),
        ),
        migrations.AddField(
            model_name='preniez',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenieces_padre', to='animales.animal'),
        ),
        migrations.AddField(
            model_name='preniez',
            name='parto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animales.parto'),
        ),
        migrations.AddField(
            model_name='preniez',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.veterinario'),
        ),
    ]
