# Generated by Django 6.0.7 on 2026-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='valor_madre',
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
    ]
