# Generated by Django 6.0.7 on 2026-08-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_movimientoanimal_pesaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias_padre', to='animales.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
