# Generated by Django 5.2.2 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_animal_foto_alter_animal_id_alter_animal_id_senasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
    ]
