# Generated by Django 6.1 on 2026-08-06 20:52

import django.db.models.deletion
from django.db import migrations, models


def asignar_establecimiento_desde_parcela(apps, schema_editor):
    """Los animales existentes heredan el establecimiento de su parcela."""
    Animal = apps.get_model('animales', 'Animal')
    for animal in Animal.objects.filter(establecimiento__isnull=True, parcela__isnull=False).select_related('parcela'):
        animal.establecimiento_id = animal.parcela.establecimiento_id
        animal.save(update_fields=['establecimiento'])


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0008_alter_animal_id_alter_movimientoanimal_id_and_more'),
        ('establecimientos', '0004_alter_establecimiento_id_alter_parcela_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='establecimientos.establecimiento'),
        ),
        migrations.RunPython(asignar_establecimiento_desde_parcela, migrations.RunPython.noop),
    ]
