# Generated by Django 6.0.7 on 2026-08-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0008_alter_animal_id_alter_movimientoanimal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='animales.parto'),
        ),
    ]
