# Generated by Django 6.0.7 on 2026-08-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0009_animal_parto'),
        ('sanidad', '0006_eventosanitario_mov_financiero'),
    ]

    operations = [
        migrations.AddField(
            model_name='preniez',
            name='evento_sanitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenieces', to='sanidad.eventosanitario'),
        ),
    ]
