# Generated by Django 6.0.7 on 2026-08-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0011_animal_idanimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preniez',
            name='costo_inseminacion',
        ),
        migrations.RemoveField(
            model_name='preniez',
            name='mov_financiero',
        ),
        migrations.RemoveField(
            model_name='preniez',
            name='veterinario',
        ),
    ]
