# Generated by Django 5.2.2 on 2026-08-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0009_animal_establecimiento'),
        ('animales', '0013_preniez_padre_donante'),
    ]

    operations = [
    ]
