# Generated by Django 5.2.2 on 2026-08-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0014_merge_20260808_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pesaje',
        ),
    ]
