# Generated by Django 6.0.7 on 2026-08-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0015_delete_pesaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoAnimal',
        ),
    ]
