# Generated by Django 5.2.2 on 2026-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0016_delete_movimientoanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_muerte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_senasa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
