# Generated by Django 6.1 on 2026-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0017_animal_fecha_muerte_alter_animal_id_senasa'),
        ('establecimientos', '0006_establecimiento_activo'),
        ('finanzas', '0009_compra_activo_movimientofinanciero_activo_and_more'),
        ('inventario', '0006_lote_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_senasa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('id_senasa',), name='animal_id_senasa_activo_uniq'),
        ),
    ]
