# Generated by Django 5.2.2 on 2026-08-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0018_animal_activo_alter_animal_id_senasa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='dieta',
        ),
    ]
