# Generated by Django 5.2.2 on 2026-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='estado',
            field=models.CharField(choices=[('En pastoreo', 'En pastoreo'), ('En descanso', 'En descanso'), ('Clausurado', 'Clausurado')], default='En pastoreo', max_length=20),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
