# Generated by Django 5.2.2 on 2026-08-02

from django.db import migrations, models


def actualizar_clausuradas(apps, schema_editor):
    Parcela = apps.get_model('establecimientos', 'Parcela')
    Parcela.objects.filter(estado='Clausurado').update(estado='En mantenimiento')


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_parcela_estado_alter_establecimiento_id_and_more'),
    ]

    operations = [
        migrations.RunPython(actualizar_clausuradas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parcela',
            name='estado',
            field=models.CharField(
                choices=[
                    ('En pastoreo', 'En pastoreo'),
                    ('En descanso', 'En descanso'),
                    ('En mantenimiento', 'En mantenimiento'),
                ],
                default='En pastoreo',
                max_length=20,
            ),
        ),
    ]
