# Generated by Django 6.1 on 2026-08-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_alter_establecimiento_id_alter_parcela_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='establecimientos/'),
        ),
    ]
