# Generated by Django 6.1 on 2026-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_establecimiento_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
