# Generated by Django 6.0.7 on 2026-07-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_zoonotica', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deteccion', models.DateField()),
                ('estado_actual', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanidad.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=150)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Vacunación', 'Vacunación'), ('Desparasitación', 'Desparasitación'), ('Antibiótico', 'Antibiótico'), ('Suplemento', 'Suplemento')], max_length=50)),
                ('fecha_aplicacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.diagnostico')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.veterinario')),
            ],
        ),
    ]
