# Generated by Django 6.0.7 on 2026-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosanitario',
            name='medicamento',
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='estado_actual',
            field=models.CharField(choices=[('Curado', 'Curado'), ('En tratamiento', 'En tratamiento'), ('Crónico', 'Crónico')], default='En tratamiento', max_length=20),
        ),
    ]
