# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_remove_eventosanitario_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosanitario',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('Vacunación', 'Vacunación'),
                    ('Desparasitación', 'Desparasitación'),
                    ('Antibiótico', 'Antibiótico'),
                    ('Suplemento', 'Suplemento'),
                    ('Castración', 'Castración'),
                ],
                max_length=50,
            ),
        ),
    ]
