# Generated by Django 6.0.7 on 2026-08-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0008_alter_animal_id_alter_movimientoanimal_id_and_more'),
        ('sanidad', '0004_eventosanitario_lote_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosanitario',
            name='animal',
        ),
        migrations.AlterField(
            model_name='eventosanitario',
            name='tipo',
            field=models.CharField(choices=[('Vacunación', 'Vacunación'), ('Desparasitación', 'Desparasitación'), ('Antibiótico', 'Antibiótico'), ('Suplemento', 'Suplemento'), ('Castración', 'Castración'), ('Inseminación', 'Inseminación')], max_length=50),
        ),
        migrations.CreateModel(
            name='DetalleEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dosis', models.DecimalField(blank=True, decimal_places=2, help_text='Dosis aplicada a este animal', max_digits=10, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_aplicados', to='animales.animal')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sanidad.eventosanitario')),
            ],
        ),
    ]
