# Generated by Django 6.0.7 on 2026-08-06 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_venta_comprador'),
        ('sanidad', '0005_remove_eventosanitario_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='mov_financiero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.movimientofinanciero'),
        ),
    ]
