# Generated by Django 6.1 on 2026-08-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0007_eventosanitario_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='padre_donante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
