# Generated by Django 6.1 on 2026-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0008_eventosanitario_padre_donante'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
