# Generated by Django 6.1 on 2026-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0008_eventosanitario_padre_donante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosanitario',
            name='tipo',
            field=models.CharField(choices=[('Vacunación', 'Vacunación'), ('Desparasitación', 'Desparasitación'), ('Antibiótico', 'Antibiótico'), ('Suplemento', 'Suplemento'), ('Castración', 'Castración'), ('Inseminación', 'Inseminación'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
