# Generated by Django 6.1 on 2026-08-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0009_alter_eventosanitario_tipo'),
        ('sanidad', '0009_eventosanitario_activo'),
    ]

    operations = [
    ]
