# Generated by Django 6.1 on 2026-08-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0010_merge_20260811_1003'),
        ('sanidad', '0010_merge_20260811_1043'),
    ]

    operations = [
    ]
