# Generated by Django 6.1 on 2026-08-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0012_alter_eventosanitario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosanitario',
            name='costo_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
