# Generated by Django 6.1 on 2026-08-10 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0005_establecimiento_logo'),
        ('usuarios', '0009_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True, default='')),
                ('icono', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('eliminada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='establecimientos.establecimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-activa', 'leida', '-creada'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'establecimiento', 'clave'), name='uniq_notificacion_por_establecimiento')],
            },
        ),
    ]
