# Generated by Django 6.1 on 2026-08-07 02:11

from django.db import migrations, models


def convertir_dueno_a_propietario(apps, schema_editor):
    RolEstablecimiento = apps.get_model('usuarios', 'RolEstablecimiento')
    RolEstablecimiento.objects.filter(nombre='Dueño').update(nombre='Propietario')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolestablecimiento',
            name='nombre',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Operario', 'Operario')], max_length=50),
        ),
        migrations.RunPython(convertir_dueno_a_propietario, migrations.RunPython.noop),
    ]
