# Generated by Django 6.1 on 2026-08-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_debe_cambiar_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
