# Generated by Django 6.1 on 2026-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('dni',), name='persona_dni_activo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('correo_electronico',), name='persona_correo_activo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre_usuario',), name='usuario_nombre_usuario_activo_uniq'),
        ),
    ]
