from django.urls import path

from inventario.views import insumo_detalle, insumo_lotes, insumos, insumos_api, lote_detalle
from . import auth_views, views

urlpatterns = [
    path('login/', auth_views.login_view, name='login'),
    path('logout/', auth_views.logout_view, name='logout'),
    path('cambiar_clave/', auth_views.cambiar_clave_view, name='cambiar_clave'),
    path('recuperar/', auth_views.recuperar_view, name='recuperar'),
    path('recuperar/<str:token>/', auth_views.restablecer_view, name='restablecer'),

    path('', views.dashboard, name='dashboard'),
    path('stock/', views.stock, name='stock'),
    path('finanzas/', views.finanzas, name='finanzas'),
    path('finanzas/ventas/', views.ventas, name='ventas'),
    path('finanzas/compras/', views.compras, name='compras'),
    path('finanzas/sueldos/', views.sueldos, name='sueldos'),
    # Se conserva la URL anterior para enlaces guardados.
    path('movimientos/', views.finanzas, name='movimientos'),
    path('parcelas/', views.potreros, name='potreros'),
    path('sanidad/', views.sanidad, name='sanidad'),
    path('vacunacion/', views.sanidad, name='vacunacion'),
    path('prenieces/', views.prenieces, name='prenieces'),
    path('api/prenieces/', views.crear_preniez, name='crear_preniez'),
    path('api/prenieces/<int:preniez_id>/', views.actualizar_preniez, name='actualizar_preniez'),
    path('api/prenieces/<int:preniez_id>/eliminar/', views.eliminar_preniez, name='eliminar_preniez'),
    path('api/prenieces/<int:preniez_id>/finalizar/', views.finalizar_preniez, name='finalizar_preniez'),
    path('api/prenieces/inseminaciones/', views.crear_evento_inseminacion, name='crear_evento_inseminacion'),
    path('api/prenieces/inseminaciones/<int:evento_id>/', views.actualizar_evento_inseminacion, name='actualizar_evento_inseminacion'),
    path('api/prenieces/inseminaciones/<int:evento_id>/eliminar/', views.eliminar_evento_inseminacion, name='eliminar_evento_inseminacion'),
    path('api/prenieces/inseminaciones/<int:evento_id>/preniadas/', views.registrar_preniadas, name='registrar_preniadas'),
    path('alimentacion/', views.alimentacion, name='alimentacion'),
    path('insumos/', insumos, name='insumos'),
    path('api/insumos/', insumos_api, name='insumos_api'),
    path('api/insumos/<int:insumo_id>/', insumo_detalle, name='insumo_detalle'),
    path('api/insumos/<int:insumo_id>/lotes/', insumo_lotes, name='insumo_lotes'),
    path('api/lotes/<int:lote_id>/', lote_detalle, name='lote_detalle'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('api/usuarios/', auth_views.crear_usuario_api, name='crear_usuario_api'),
    path('api/usuarios/<int:usuario_id>/', auth_views.actualizar_usuario_api, name='actualizar_usuario_api'),
    path('api/usuarios/<int:usuario_id>/eliminar/', auth_views.eliminar_usuario_api, name='eliminar_usuario_api'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('api/stock/', views.stock_api, name='stock_api'),
    path('api/animales/', views.crear_animal, name='crear_animal'),
    path('api/animales/<int:animal_id>/', views.actualizar_animal, name='actualizar_animal'),
    path('api/animales/<int:animal_id>/eliminar/', views.eliminar_animal, name='eliminar_animal'),
    path('api/sanidad/eventos/', views.crear_evento_sanitario, name='crear_evento_sanitario'),
    path('api/sanidad/eventos/<int:evento_id>/', views.actualizar_evento_sanitario, name='actualizar_evento_sanitario'),
    path('api/sanidad/eventos/<int:evento_id>/eliminar/', views.eliminar_evento_sanitario, name='eliminar_evento_sanitario'),
    path('api/sanidad/enfermedades/', views.crear_enfermedad, name='crear_enfermedad'),
    path('api/sanidad/enfermedades/<int:enfermedad_id>/', views.actualizar_enfermedad, name='actualizar_enfermedad'),
    path('api/sanidad/enfermedades/<int:enfermedad_id>/eliminar/', views.eliminar_enfermedad, name='eliminar_enfermedad'),
    path('api/sanidad/diagnosticos/', views.crear_diagnostico, name='crear_diagnostico'),
    path('api/sanidad/diagnosticos/<int:diagnostico_id>/', views.actualizar_diagnostico, name='actualizar_diagnostico'),
    path('api/sanidad/diagnosticos/<int:diagnostico_id>/eliminar/', views.eliminar_diagnostico, name='eliminar_diagnostico'),
    path('api/sanidad/veterinarios/', views.crear_veterinario, name='crear_veterinario'),
    path('api/sanidad/veterinarios/<int:veterinario_id>/', views.actualizar_veterinario, name='actualizar_veterinario'),
    path('api/sanidad/veterinarios/<int:veterinario_id>/eliminar/', views.eliminar_veterinario, name='eliminar_veterinario'),
    path('api/movimientos/', views.crear_movimiento, name='crear_movimiento'),
    path('api/finanzas/movimientos/', views.finanzas_api_list_create, name='api_finanzas_movimientos'),
    path('api/finanzas/movimientos/<int:movimiento_id>/', views.actualizar_movimiento_financiero, name='actualizar_movimiento_financiero'),
    path('api/finanzas/movimientos/<int:movimiento_id>/eliminar/', views.eliminar_movimiento_financiero, name='eliminar_movimiento_financiero'),
    path('api/compradores/', views.crear_comprador, name='crear_comprador'),
    path('api/compradores/<int:comprador_id>/', views.actualizar_comprador, name='actualizar_comprador'),
    path('api/compradores/<int:comprador_id>/eliminar/', views.eliminar_comprador, name='eliminar_comprador'),
    path('api/proveedores/', views.crear_proveedor, name='crear_proveedor'),
    path('api/proveedores/<int:proveedor_id>/', views.actualizar_proveedor, name='actualizar_proveedor'),
    path('api/proveedores/<int:proveedor_id>/eliminar/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('api/compras/', views.crear_compra, name='crear_compra'),
    path('api/compras/<int:compra_id>/', views.actualizar_compra, name='actualizar_compra'),
    path('api/compras/<int:compra_id>/eliminar/', views.eliminar_compra, name='eliminar_compra'),
    path('api/ventas/', views.crear_venta, name='crear_venta'),
    path('api/ventas/<int:venta_id>/', views.actualizar_venta, name='actualizar_venta'),
    path('api/ventas/<int:venta_id>/eliminar/', views.eliminar_venta, name='eliminar_venta'),
    path('api/liquidaciones/', views.crear_liquidacion, name='crear_liquidacion'),
    path('api/liquidaciones/<int:liquidacion_id>/', views.actualizar_liquidacion, name='actualizar_liquidacion'),
    path('api/liquidaciones/<int:liquidacion_id>/eliminar/', views.eliminar_liquidacion, name='eliminar_liquidacion'),
    path('api/parcelas/', views.crear_potrero, name='crear_potrero'),
    path('api/parcelas/<int:parcela_id>/eliminar/', views.eliminar_potrero, name='eliminar_potrero'),
    path('api/establecimientos/', views.establecimientos_api, name='establecimientos_api'),
    path('api/establecimientos/seleccionar/', views.seleccionar_establecimiento, name='seleccionar_establecimiento'),
    path('api/establecimientos/crear/', views.crear_establecimiento, name='crear_establecimiento'),
    path('api/establecimientos/<int:establecimiento_id>/eliminar/', views.eliminar_establecimiento, name='eliminar_establecimiento'),
    path('api/establecimientos/config/', views.config_establecimiento_api, name='config_establecimiento_api'),
]
